namespace RCaron.AutoCompletion;

public class CompletionThing
{
    public required string Word { get; set; }
    public required CompletionItemKind Kind { get; set; }

    /// <summary>
    /// In case Detail is getting autogenerated, preface it with this.
    /// </summary>
    public string? DetailPreface { get; set; }

    public string? Detail { get; set; }

    /// <summary>
    /// Documentation in markdown. Should 
    /// </summary>
    public string? Documentation { get; set; }

    public bool Deprecated { get; set; } = false;
    public CompletionItemModifier Modifier { get; set; } = CompletionItemModifier.None;
}